"""
CareerLens AI — FastAPI backend entrypoint.

Run locally (after `pip install -r requirements.txt` with internet access):
    uvicorn app.main:app --reload --port 8000
Docs then live at http://localhost:8000/docs (auto-generated by FastAPI).
"""
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from app.config import settings
from app.api import resume, jobs, matching, career

app = FastAPI(
    title="CareerLens AI API",
    description="AI-powered resume intelligence, ATS-style analysis, and semantic job matching.",
    version="0.1.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---- global error handling: never leak raw stack traces to the client (spec §36) ----
@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    # In production this should also log exc with a request-id for debugging.
    return JSONResponse(
        status_code=500,
        content={"error": "internal_server_error", "message": "Something went wrong processing your request."},
    )


@app.get("/health", tags=["system"])
async def health_check():
    return {"status": "ok", "service": "careerlens-ai-backend"}


app.include_router(resume.router, prefix="/api/resume", tags=["resume"])
app.include_router(jobs.router, prefix="/api/jobs", tags=["jobs"])
app.include_router(matching.router, prefix="/api", tags=["matching"])
app.include_router(career.router, prefix="/api", tags=["career"])
